// <auto-generated />
namespace Kiarah.LittleXavier.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddMyFamily : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMyFamily));
        
        string IMigrationMetadata.Id
        {
            get { return "201504190037431_AddMyFamily"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
